"""Self-contained HTML report generation for eval runs and comparisons."""
from __future__ import annotations

import html
from datetime import datetime, timezone

# Dark theme colours (same as dashboard)
_BG = "#111113"
_SURFACE = "#1a1a1e"
_ACCENT = "#fb923c"
_GREEN = "#4ade80"
_RED = "#f87171"
_TEXT = "#e4e4e7"
_MUTED = "#a1a1aa"
_BORDER = "#27272a"

_BASE_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    background: %(bg)s;
    color: %(text)s;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6;
    padding: 2rem;
}
.container { max-width: 900px; margin: 0 auto; }
h1 { color: %(accent)s; margin-bottom: 0.5rem; font-size: 1.5rem; }
h2 { color: %(text)s; margin-top: 1.5rem; margin-bottom: 0.75rem; font-size: 1.15rem; }
.subtitle { color: %(muted)s; font-size: 0.85rem; margin-bottom: 1.5rem; }
.card {
    background: %(surface)s;
    border: 1px solid %(border)s;
    border-radius: 8px;
    padding: 1.25rem;
    margin-bottom: 1rem;
}
table {
    width: 100%%;
    border-collapse: collapse;
    margin-bottom: 1rem;
    font-size: 0.9rem;
}
th, td {
    text-align: left;
    padding: 0.5rem 0.75rem;
    border-bottom: 1px solid %(border)s;
}
th { color: %(muted)s; font-weight: 600; }
.pass { color: %(green)s; font-weight: 600; }
.fail { color: %(red)s; font-weight: 600; }
.score { color: %(accent)s; }
.badge {
    display: inline-block;
    padding: 0.15rem 0.6rem;
    border-radius: 4px;
    font-size: 0.8rem;
    font-weight: 600;
}
.badge-pass { background: %(green)s22; color: %(green)s; }
.badge-fail { background: %(red)s22; color: %(red)s; }
.badge-switch { background: %(green)s22; color: %(green)s; }
.badge-keep { background: %(red)s22; color: %(red)s; }
.badge-comparable { background: %(accent)s22; color: %(accent)s; }
.verdict-box {
    background: %(surface)s;
    border: 1px solid %(border)s;
    border-radius: 8px;
    padding: 1.25rem;
    margin-top: 1.5rem;
}
.muted { color: %(muted)s; }
.footer { color: %(muted)s; font-size: 0.75rem; margin-top: 2rem; text-align: center; }
""" % {
    "bg": _BG,
    "surface": _SURFACE,
    "accent": _ACCENT,
    "green": _GREEN,
    "red": _RED,
    "text": _TEXT,
    "muted": _MUTED,
    "border": _BORDER,
}


def _esc(value: object) -> str:
    """HTML-escape any value."""
    return html.escape(str(value))


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _wrap_html(title: str, body: str) -> str:
    return (
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "  <title>{title}</title>\n"
        "  <style>{css}</style>\n"
        "</head>\n"
        "<body>\n"
        "<div class=\"container\">\n"
        "{body}\n"
        "<div class=\"footer\">Generated by promptry &middot; {ts}</div>\n"
        "</div>\n"
        "</body>\n"
        "</html>"
    ).format(title=_esc(title), css=_BASE_CSS, body=body, ts=_timestamp())


# ---------------------------------------------------------------------------
# Run report
# ---------------------------------------------------------------------------

def render_run_report(results: dict) -> str:
    """Render eval run results as a self-contained HTML page.

    Expects a dict shaped like a serialised ``SuiteResult``:
        suite_name, overall_pass, overall_score, tests (list of dicts with
        test_name, passed, latency_ms, error, assertions [...]).
    """
    suite_name = results.get("suite_name", "unknown")
    overall_pass = results.get("overall_pass", False)
    overall_score = results.get("overall_score", 0.0)
    tests = results.get("tests", [])

    pass_class = "pass" if overall_pass else "fail"
    pass_label = "PASS" if overall_pass else "FAIL"
    badge_class = "badge-pass" if overall_pass else "badge-fail"

    # Header
    parts: list[str] = []
    parts.append(
        "<h1>Eval Run Report</h1>\n"
        "<p class=\"subtitle\">Suite: <strong>{suite}</strong></p>".format(
            suite=_esc(suite_name),
        )
    )

    # Summary card
    parts.append(
        "<div class=\"card\">\n"
        "  <table>\n"
        "    <tr><th>Suite</th><td>{suite}</td></tr>\n"
        "    <tr><th>Result</th><td><span class=\"badge {badge}\">{label}</span></td></tr>\n"
        "    <tr><th>Score</th><td class=\"score\">{score:.3f}</td></tr>\n"
        "    <tr><th>Tests</th><td>{n_tests}</td></tr>\n"
        "  </table>\n"
        "</div>".format(
            suite=_esc(suite_name),
            badge=badge_class,
            label=pass_label,
            score=overall_score,
            n_tests=len(tests),
        )
    )

    # Per-test results
    if tests:
        parts.append("<h2>Test Results</h2>")
        for test in tests:
            t_name = test.get("test_name", "?")
            t_pass = test.get("passed", False)
            t_latency = test.get("latency_ms", 0.0)
            t_error = test.get("error")
            assertions = test.get("assertions", [])

            t_status_class = "pass" if t_pass else "fail"
            t_status_label = "PASS" if t_pass else "FAIL"

            parts.append(
                "<div class=\"card\">\n"
                "  <h2 style=\"margin-top:0\">"
                "<span class=\"{cls}\">{label}</span> {name}"
                " <span class=\"muted\" style=\"font-weight:normal; font-size:0.85rem\">"
                "({latency:.0f}ms)</span></h2>".format(
                    cls=t_status_class,
                    label=t_status_label,
                    name=_esc(t_name),
                    latency=t_latency,
                )
            )

            if t_error:
                parts.append(
                    "  <p class=\"fail\" style=\"margin-bottom:0.75rem\">{err}</p>".format(
                        err=_esc(t_error),
                    )
                )

            if assertions:
                parts.append(
                    "  <table>\n"
                    "    <tr><th>Assertion</th><th>Score</th><th>Status</th></tr>"
                )
                for a in assertions:
                    a_type = a.get("assertion_type", "?")
                    a_score = a.get("score")
                    a_passed = a.get("passed", False)
                    score_str = "{:.3f}".format(a_score) if a_score is not None else "-"
                    a_cls = "pass" if a_passed else "fail"
                    a_label = "ok" if a_passed else "FAIL"
                    parts.append(
                        "    <tr>"
                        "<td>{atype}</td>"
                        "<td class=\"score\">{score}</td>"
                        "<td class=\"{cls}\">{label}</td>"
                        "</tr>".format(
                            atype=_esc(a_type),
                            score=score_str,
                            cls=a_cls,
                            label=a_label,
                        )
                    )
                parts.append("  </table>")

            parts.append("</div>")

    return _wrap_html("promptry - {} run report".format(suite_name), "\n".join(parts))


# ---------------------------------------------------------------------------
# Compare report
# ---------------------------------------------------------------------------

def render_compare_report(data: dict) -> str:
    """Render model comparison as a self-contained HTML page.

    Expects a dict shaped like a serialised ``ModelCompareReport``:
        suite_name, baseline {model_version, run_count, overall_mean, ...},
        candidate {model_version, run_count, overall_mean, ...},
        overall_delta, percentile, assertion_comparisons [...],
        cost_ratio, score_per_dollar_baseline, score_per_dollar_candidate,
        verdict, verdict_reason.
    """
    suite_name = data.get("suite_name", "unknown")
    baseline = data.get("baseline", {})
    candidate = data.get("candidate", {})
    verdict = data.get("verdict", "comparable")
    verdict_reason = data.get("verdict_reason", "")
    overall_delta = data.get("overall_delta", 0.0)
    percentile = data.get("percentile", 50.0)
    assertion_comparisons = data.get("assertion_comparisons", [])
    cost_ratio = data.get("cost_ratio")
    spd_baseline = data.get("score_per_dollar_baseline")
    spd_candidate = data.get("score_per_dollar_candidate")

    b_model = baseline.get("model_version", "?")
    b_runs = baseline.get("run_count", 0)
    b_mean = baseline.get("overall_mean", 0.0)
    b_std = baseline.get("overall_std", 0.0)
    b_min = baseline.get("overall_min", 0.0)
    b_max = baseline.get("overall_max", 0.0)
    b_cost = baseline.get("avg_cost_per_call", 0.0)

    c_model = candidate.get("model_version", "?")
    c_runs = candidate.get("run_count", 0)
    c_mean = candidate.get("overall_mean", 0.0)
    c_cost = candidate.get("avg_cost_per_call", 0.0)

    verdict_upper = verdict.upper().replace("_", " ")
    if verdict == "switch":
        v_badge = "badge-switch"
    elif verdict == "keep_baseline":
        v_badge = "badge-keep"
    else:
        v_badge = "badge-comparable"

    parts: list[str] = []

    # Header
    parts.append(
        "<h1>Model Comparison Report</h1>\n"
        "<p class=\"subtitle\">Suite: <strong>{suite}</strong></p>".format(
            suite=_esc(suite_name),
        )
    )

    # Summary card
    parts.append(
        "<div class=\"card\">\n"
        "  <table>\n"
        "    <tr><th></th><th>{b_model} (baseline)</th><th>{c_model} (candidate)</th></tr>\n"
        "    <tr><th>Runs</th><td>{b_runs}</td><td>{c_runs}</td></tr>\n"
        "    <tr><th>Mean Score</th>"
        "<td class=\"score\">{b_mean:.3f} &plusmn; {b_std:.3f}</td>"
        "<td class=\"score\">{c_mean:.3f}</td></tr>\n"
        "    <tr><th>Range</th>"
        "<td class=\"muted\">{b_min:.3f} &mdash; {b_max:.3f}</td>"
        "<td class=\"muted\">&Delta; {delta:+.3f} ({pctl:.0f}th pctl)</td></tr>\n"
        "  </table>\n"
        "</div>".format(
            b_model=_esc(b_model),
            c_model=_esc(c_model),
            b_runs=b_runs,
            c_runs=c_runs,
            b_mean=b_mean,
            b_std=b_std,
            c_mean=c_mean,
            b_min=b_min,
            b_max=b_max,
            delta=overall_delta,
            pctl=percentile,
        )
    )

    # Per-assertion breakdown
    if assertion_comparisons:
        parts.append("<h2>Per-Assertion Comparison</h2>")
        parts.append(
            "<div class=\"card\">\n"
            "  <table>\n"
            "    <tr><th>Assertion</th><th>Baseline</th><th>Candidate</th>"
            "<th>Delta</th><th>Verdict</th></tr>"
        )
        for ac in assertion_comparisons:
            a_type = ac.get("assertion_type", "?")
            a_b_mean = ac.get("baseline_mean", 0.0)
            a_b_std = ac.get("baseline_std", 0.0)
            a_c_score = ac.get("candidate_score", 0.0)
            a_delta = ac.get("delta", 0.0)
            a_verdict = ac.get("verdict", "comparable")

            if a_verdict == "better":
                v_cls = "pass"
            elif a_verdict == "worse":
                v_cls = "fail"
            else:
                v_cls = "muted"

            parts.append(
                "    <tr>"
                "<td>{atype}</td>"
                "<td class=\"score\">{b_mean:.3f} &plusmn; {b_std:.3f}</td>"
                "<td class=\"score\">{c_score:.3f}</td>"
                "<td>{delta:+.3f}</td>"
                "<td class=\"{v_cls}\">{verdict}</td>"
                "</tr>".format(
                    atype=_esc(a_type),
                    b_mean=a_b_mean,
                    b_std=a_b_std,
                    c_score=a_c_score,
                    delta=a_delta,
                    v_cls=v_cls,
                    verdict=a_verdict,
                )
            )
        parts.append("  </table>\n</div>")

    # Cost analysis
    if cost_ratio is not None:
        pct = abs(1 - cost_ratio) * 100
        direction = "cheaper" if cost_ratio < 1 else "more expensive"

        parts.append("<h2>Cost Analysis</h2>")
        parts.append(
            "<div class=\"card\">\n"
            "  <table>\n"
            "    <tr><th></th><th>{b_model}</th><th>{c_model}</th></tr>\n"
            "    <tr><th>Cost / call</th>"
            "<td>${b_cost:.4f}</td><td>${c_cost:.4f}</td></tr>\n"
            "    <tr><th>Relative</th>"
            "<td colspan=\"2\">Candidate is {pct:.0f}% {direction}</td></tr>".format(
                b_model=_esc(b_model),
                c_model=_esc(c_model),
                b_cost=b_cost,
                c_cost=c_cost,
                pct=pct,
                direction=direction,
            )
        )
        if spd_baseline is not None and spd_candidate is not None:
            parts.append(
                "    <tr><th>Score / $</th>"
                "<td>{spd_b:.0f}</td><td>{spd_c:.0f}</td></tr>".format(
                    spd_b=spd_baseline,
                    spd_c=spd_candidate,
                )
            )
        parts.append("  </table>\n</div>")

    # Verdict
    parts.append(
        "<div class=\"verdict-box\">\n"
        "  <h2 style=\"margin-top:0\">Verdict: "
        "<span class=\"badge {v_badge}\">{verdict}</span></h2>\n"
        "  <p>{reason}</p>\n"
        "</div>".format(
            v_badge=v_badge,
            verdict=_esc(verdict_upper),
            reason=_esc(verdict_reason),
        )
    )

    return _wrap_html(
        "promptry - {} comparison".format(suite_name),
        "\n".join(parts),
    )
